2016-02-05 20:26:07
Traceback (most recent call last):
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SFTP/sftp/threads.py", line 15, in run_with_except_hook
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SFTP/sftp/commands.py", line 1914, in run
  File "./shutil.py", line 478, in rmtree
  File "./shutil.py", line 377, in _rmtree_unsafe
  File "./shutil.py", line 375, in _rmtree_unsafe
PermissionError: [WinError 32] Процесс не может получить доступ к файлу, так как этот файл занят другим процессом: 'E:\\sftp\\nodedeveloper.ru\\js\\'
2016-02-05 20:26:23
Traceback (most recent call last):
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SFTP/sftp/threads.py", line 15, in run_with_except_hook
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SFTP/sftp/commands.py", line 1914, in run
  File "./shutil.py", line 478, in rmtree
  File "./shutil.py", line 377, in _rmtree_unsafe
  File "./shutil.py", line 375, in _rmtree_unsafe
PermissionError: [WinError 32] Процесс не может получить доступ к файлу, так как этот файл занят другим процессом: 'E:\\sftp\\nodedeveloper.ru\\js\\'
2016-02-06 14:43:12
Traceback (most recent call last):
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SFTP/sftp/threads.py", line 15, in run_with_except_hook
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SFTP/sftp/commands.py", line 1914, in run
  File "./shutil.py", line 478, in rmtree
  File "./shutil.py", line 377, in _rmtree_unsafe
  File "./shutil.py", line 375, in _rmtree_unsafe
PermissionError: [WinError 32] Процесс не может получить доступ к файлу, так как этот файл занят другим процессом: 'E:\\sftp\\nodedeveloper.ru\\views\\css\\'
